USE HH_TEST_TASK;

SELECT 
	PRODUCTS.NAME AS ProductName,
	CATEGORIES.NAME AS CategoryName
FROM
	PRODUCTS 
		LEFT JOIN PRODUCTS_TO_CATEGORIES ON PRODUCTS_TO_CATEGORIES.PRODUCT_ID = PRODUCTS.ID
		LEFT JOIN CATEGORIES ON CATEGORIES.ID = PRODUCTS_TO_CATEGORIES.CATEGORY_ID